services:
  db:
    image: postgres:15-alpine
    container_name: voltcloud_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: voltcloud
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: voltcloud_app
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:1234@db:5432/voltcloud?schema=public"
      BOT_TOKEN: ${BOT_TOKEN}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    ports:
      - "2020:3000"
    depends_on:
      - db

volumes:
  postgres_data: